name: AutoBroadcaster
main: me.skipperguy12.AutoBroadcasterPlus.AutoBroadcasterPlus
version: 0.4
description: AutoBroadcasterPlus by skipperguy12
commands:
    ab:
        description: Core command for AutoBroadcaster