broadcaster:
    #Who will be the announcer? Ex: [AutoBroadcaster]: Message
    announcerName: '[&4AutoBroadcaster&f]: '

    #Interval, in seconds
    interval: 60

    #Should the plugin debug?
    debugging: false